package com.mycompany.scheduler.model;
// Generated Jan 27, 2018 12:21:46 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Appointment generated by hbm2java
 */
public class Appointment  implements java.io.Serializable {


     private int appointmentId;
     private int customerId;
     private String title;
     private String description;
     private String location;
     private String contact;
     private String url;
     private Date start;
     private Date end;
     private Date createDate;
     private String createdBy;
     private Date lastUpdate;
     private String lastUpdateBy;

    public Appointment() {
    }

    public Appointment(int appointmentId, int customerId, String title, String description, String location, String contact, String url, Date start, Date end, Date createDate, String createdBy, Date lastUpdate, String lastUpdateBy) {
       this.appointmentId = appointmentId;
       this.customerId = customerId;
       this.title = title;
       this.description = description;
       this.location = location;
       this.contact = contact;
       this.url = url;
       this.start = start;
       this.end = end;
       this.createDate = createDate;
       this.createdBy = createdBy;
       this.lastUpdate = lastUpdate;
       this.lastUpdateBy = lastUpdateBy;
    }
   
    public int getAppointmentId() {
        return this.appointmentId;
    }
    
    public void setAppointmentId(int appointmentId) {
        this.appointmentId = appointmentId;
    }
    public int getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public Date getStart() {
        return this.start;
    }
    
    public void setStart(Date start) {
        this.start = start;
    }
    public Date getEnd() {
        return this.end;
    }
    
    public void setEnd(Date end) {
        this.end = end;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    public String getLastUpdateBy() {
        return this.lastUpdateBy;
    }
    
    public void setLastUpdateBy(String lastUpdateBy) {
        this.lastUpdateBy = lastUpdateBy;
    }




}


