package com.mycompany.scheduler.model;
// Generated Jan 27, 2018 12:21:46 PM by Hibernate Tools 4.3.1

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;


/**
 * Incrementtypes generated by hbm2java
 */
public class Incrementtypes implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private int incrementTypeId;
    private String incrementTypeDescription;

    public Incrementtypes() {
    }

    public Incrementtypes(int incrementTypeId, String incrementTypeDescription) {
        this.incrementTypeId = incrementTypeId;
        this.incrementTypeDescription = incrementTypeDescription;
    }

    public int getIncrementTypeId() {
        return this.incrementTypeId;
    }

    public void setIncrementTypeId(int incrementTypeId) {
        this.incrementTypeId = incrementTypeId;
    }

    public String getIncrementTypeDescription() {
        return this.incrementTypeDescription;
    }

    public void setIncrementTypeDescription(String incrementTypeDescription) {
        this.incrementTypeDescription = incrementTypeDescription;
    }

}
